blueprint:
  name: Sincronizar luzes ou interruptores
  description: Acione uma entidade e a outra seguirá o mesmo estado.
  domain: automation
  input:
    master_entity:
      name: Entidade Mestre
      description: Esta entidade quando acionada irá sincronizar o estado com a entidade escrava.
      selector:
        entity:
          domain:
            - light
            - switch
    slave_entity:
      name: Entidade Escrava
      description: Esta entidade terá seu estado sincronizado com a entidade mestre.
      selector:
        entity:
          domain:
            - light
            - switch

trigger:
  - platform: state
    entity_id: !input master_entity
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: !input master_entity
    from: 'on'
    to: 'off'

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input master_entity
            state: 'on'
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input slave_entity
      - conditions:
          - condition: state
            entity_id: !input master_entity
            state: 'off'
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input slave_entity
